"""empty message

Revision ID: 4959e345eda2
Revises: 4240ed4f83ef
Create Date: 2022-10-13 18:10:50.355247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4959e345eda2'
down_revision = '4240ed4f83ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expression', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.add_column('expression', sa.Column('student_id', sa.Integer(), nullable=False))
    op.drop_column('expression', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expression', sa.Column('date', mysql.DATETIME(), nullable=True))
    op.drop_column('expression', 'student_id')
    op.drop_column('expression', 'date_time')
    # ### end Alembic commands ###
