"""empty message

Revision ID: a0e124f11dbf
Revises: cfd16846bd0b
Create Date: 2022-10-25 16:17:01.844621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e124f11dbf'
down_revision = 'cfd16846bd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin', ['email'])
    op.create_unique_constraint(None, 'course', ['course_code'])
    op.create_unique_constraint(None, 'student', ['student_number'])
    op.create_unique_constraint(None, 'student', ['email'])
    op.create_unique_constraint(None, 'teacher', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='unique')
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_constraint(None, 'course', type_='unique')
    op.drop_constraint(None, 'admin', type_='unique')
    # ### end Alembic commands ###
